"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-08-01 18:52:23.282211
"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('coordinator', 'approver', 'admin')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('complaints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('complaint_number', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('complaint_source', sa.String(length=255), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('product_strength_grade', sa.String(length=100), nullable=True),
    sa.Column('batch_lot_number', sa.String(length=100), nullable=True),
    sa.Column('manufacturing_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('quantity_affected', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('quantity_affected_unit', sa.String(length=20), nullable=True),
    sa.Column('complaint_type', sa.String(length=100), nullable=True),
    sa.Column('complaint_date', sa.Date(), nullable=True),
    sa.Column('complaint_description', sa.Text(), nullable=True),
    sa.Column('initial_severity', sa.String(length=20), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('ai_risk_severity_suggested', sa.String(length=20), nullable=True),
    sa.Column('ai_risk_next_action_suggested', sa.Text(), nullable=True),
    sa.Column('ai_risk_assessment_narrative', sa.Text(), nullable=True),
    sa.Column('ai_root_cause_hypotheses', sa.JSON(), nullable=True),
    sa.Column('root_cause_accepted', sa.Text(), nullable=True),
    sa.Column('ai_capa_corrective_suggested', sa.Text(), nullable=True),
    sa.Column('ai_capa_preventive_suggested', sa.Text(), nullable=True),
    sa.Column('capa_accepted', sa.Text(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('field_provenance', sa.JSON(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approval_reason', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('trashed_by', sa.UUID(), nullable=True),
    sa.Column('trashed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('purge_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending_approval', 'pending_rework_triage', 'approved_closed', 'trashed')", name='ck_complaints_status'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['trashed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaints_batch_lot_number'), 'complaints', ['batch_lot_number'], unique=False)
    op.create_index(op.f('ix_complaints_complaint_number'), 'complaints', ['complaint_number'], unique=True)
    op.execute(
        "CREATE INDEX complaints_embedding_idx ON complaints "
        "USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100)"
    )
    op.create_table('attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('complaint_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind IN ('source_document', 'evidence')", name='ck_attachments_kind'),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachments_complaint_id'), 'attachments', ['complaint_id'], unique=False)
    op.create_table('audit_log_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('complaint_id', sa.UUID(), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("source IN ('ai', 'human', 'system')", name='ck_audit_log_entries_source'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_entries_complaint_id'), 'audit_log_entries', ['complaint_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_log_entries_complaint_id'), table_name='audit_log_entries')
    op.drop_table('audit_log_entries')
    op.drop_index(op.f('ix_attachments_complaint_id'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index('complaints_embedding_idx', table_name='complaints')
    op.drop_index(op.f('ix_complaints_complaint_number'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_batch_lot_number'), table_name='complaints')
    op.drop_table('complaints')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # Intentionally not dropping the vector extension here: it is a shared
    # Postgres extension and other objects in the database may depend on it,
    # so downgrading this migration should not risk breaking them.
    # ### end Alembic commands ###
